apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-content
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /c/Users/lautaro/web-content
    type: Directory
