apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-web #Debe coincidir con el app: nginx-web de tu Deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
